### ISSUE TITLE
.zip created with merged.hex is too large

### ISSUE THREAD

**Issue by vincentkyeh** [gamnes/nRF52832-buttonless-dfu-development-tutorial#1]
Hi -- I just wanted to start by saying this tutorial is fantastic!

Still, I've been running into an issue. I've been trying to get DFU on my project, but I saw that the DFU would work, but my application would not boot (it would be stuck in DfuTarg mode).

I figured this was a result of lacking a bootloader settings page, so I created one following your guide and merged it with my application .hex file.

The .hex files make sense:
app.hex is 356 kB
settings.hex is 4 kB
merged.hex is 364 kB

However, when I create the packages using app.hex and merged.hex, the output file sizes are VASTLY different to the point where the one created by merged.hex cause an "INSUFFICIENT RESOURCES" error during DFU.

package created with app.hex: 130 kB
package created with merged.hex: 378 kB

I can't find a workaround. Either the DFU works and the application does not boot, or the DFU is unable to work at all due to the large package size. Is there any insight as to why the packages are so different in size just as a result of the bootloader settings?

**Comment by gamnes** [comment]
Hi, thanks!

Its been a while since i worked on this, but let me try to see if i can help. Did you run through my example - and that worked?

If the application gets stuck in DfuTarg mode - its because the bootloader does not find a valid application (or no application at all). You need the bootloader settings page to fix this. 

Are you trying to upload both application and softdevice? Or application only?
Also when you do a DFU, there needs to be enough "scratch" space (i believe) for the image you are trying to install, so if the package you create is too big, the DFU cannot successfully run because there isnt enough space for it. Is that what is happening, maybe?

I assume when you write package - that is the .zip package used when transmitting the new FW over the air? This package should not include the settings part - as the DFU logic takes care of writing the new settings into memory when the new application is received. The settings are only needed if the FW is placed in memory directly. If the FW is placed in memory by the DFU logic - it will write the settings itself.

**Comment by vincentkyeh** [comment]
Hi, thanks for responding!

Yes, I used your example and it worked. I was able to get the Nordic_UART application to boot after the DFU process and I could see it advertising as "Nordic_UART". However, my custom application that I built myself does not seem to work.

Let me try to explain the symptoms of what is happening when I perform DFU with my own application:
1.) I create the .zip package (I've done it with SD+app as well as app alone. Results are the same).
2.) I upload it via DFU and it works! If there is SD, it runs twice. Once for the SD, once for the app although the end result is the same.
3.) The DK has no LEDs lit up except for LED5 (my custom application is supposed to blink LED1).
4.) There is no Bluetooth advertising; I tried sniffing it with Nordic Toolbox, nRF Connect, and LightBlue).
5.) At this point, I think it keeps boot-cycling itself because if i press Button4 (WITHOUT pressing RESET or power-cycling via the switch), LED1 and LED2 will light up and it will start advertising as "DfuTarg".
6.) There is no way to get the application to boot up at this point.

Here, I thought it was because I was missing my bootloader page settings, so I tried to merge a settings.hex file with my app.hex file, but the resulting .zip file became too large to be sent over DFU. However, you mentioned that files written via DFU will automatically have settings be taken care of, so I longer know what the problem might be.

I also want to mention that if I drag and drop my custom app.hex file into the JLINK drive to flash the DK, my application will run although it will not be able to support any kind of DFU. When I try to perform DFU, it says "NO DFU CHARACTERISTICS FOUND". I'm assuming dragging and dropping my custom app.hex file overrides the DFU bootloader, but I honestly am not sure at this point.

I am compiling via mBed Command Line Interface with the command "mbed compile -t GCC_ARM -m NRF52_DK". Does this have anything to do with it? Do I have to compile through SES? My project relies on some of the mbed-os libraries.

**Comment by gamnes** [comment]
Does your custom application run fine without the bootloader in place? 
Does your custom application run fine after the first programming when it is merged with bootloader, softdevice and settings page?

Is there a bug in your application that is causing the reboot? (what happens if in your application the __only_ thing you do is to toggle some LEDs in a while(true))?

If you drag and drop - the entire flash content will be erased and replaced with the file you drag and dropped; so yes, it overrides everything that is on there from before.

I'm sure compiling through mbed should be fine although i have not tested that in a while. You might want to open a support ticket for this on https://devzone.nordicsemi.com/ and ask these questions there. Thanks.

**Comment by vincentkyeh** [comment]
I'm still trying to figure things out, but I've definitely made leaps and bounds in my progress thanks to your guide and your responses here. :)

I understand it's probably a lot of effort to help me debug here, so I appreciate what you've helped me with thus far. I think I can take it from here on my own -- I'll need to learn on my own after all! I wish you the best in continuing your good work. Thanks gamnes.

**Comment by gamnes** [comment]
Good luck!:) Thanks
